import * as FaIcons from "react-icons/fa";

export const iconMap = {
  FaAward: FaIcons.FaAward,
  FaCalendar: FaIcons.FaCalendar,
  FaPlayCircle: FaIcons.FaPlayCircle,
  FaTrophy: FaIcons.FaTrophy,
  FaLightbulb: FaIcons.FaLightbulb,
  FaUsers: FaIcons.FaUsers,
  FaMedal: FaIcons.FaMedal,
  FaHandshake: FaIcons.FaHandshake,
  FaLeaf: FaIcons.FaLeaf,
  FaFacebook: FaIcons.FaFacebook,
  FaInstagram: FaIcons.FaInstagram,
  FaPinterestP: FaIcons.FaPinterestP,
  FaLinkedinIn: FaIcons.FaLinkedinIn,
  FaHome: FaIcons.FaHome,
  FaClock: FaIcons.FaClock,
  FaEnvelope: FaIcons.FaEnvelope,
  FaMapMarkerAlt: FaIcons.FaMapMarkerAlt,
  FaPhoneAlt: FaIcons.FaPhoneAlt,
  FaFacebookF: FaIcons.FaFacebookF,
  FaCube: FaIcons.FaCube,
  FaDraftingCompass: FaIcons.FaDraftingCompass,
  FaExpandArrowsAlt: FaIcons.FaExpandArrowsAlt,
  FaHardHat: FaIcons.FaHardHat,
  FaPaintRoller: FaIcons.FaPaintRoller,
  FaQuestionCircle: FaIcons.FaQuestionCircle,
};
